### ISSUE TITLE
Program launch failure

### ISSUE THREAD

**Issue by vatterspun** [henrypp/freeshooter#1]
Setup: Win7x86

Steps: 
1. Download and extract freeshooter_1.9.6_bin.7z
2. Launch _freeshooter.exe_

Defect: Nothing happens.  Is this 64-bit only?

**Comment by henrypp** [comment]
on win7 64-bit working well
32-bit supported

**Comment by vatterspun** [comment]
I don't know what went wrong at my initial test this morning but the process works now.  Closing the case.
