### ISSUE TITLE
наблюдение

### ISSUE THREAD

**Issue by perdolka** [henrypp/freeshooter#10]
Может я невнимательно смотрел, но, кажется ни на сайте, ни в README.md здесь, ни в самой программе - нигде не задокументировано, что можно открывать папку скриншотов кликом СКМ по иконке в трее.
А ведь это супер-удобная фича.

Догадался только интуитивно, потому что ранее использовал вашу программу memreduct, 
в которой на СКМ есть функционал и это задокументировано в настройках программы.

**Comment by henrypp** [comment]
Да, мне тоже удобно!
