### ISSUE TITLE
ENhancement: offer more choices for the hotkey 

### ISSUE THREAD

**Issue by Janaue** [henrypp/freeshooter#17]
Hello,

i often use your program and I would like to use the hotkey ''right shift'' plus its adjacent key which is ? since half the time,  I take the picture with my right hand. Currently, I use ''shift+f4'' and it works well for the left hand. Can you offer more  choices for the hotkeys ?

**Comment by henrypp** [comment]
Shift are worked RSHIFT & LSHIFT as well, but not standalone.
Predefined keys will extended in next release.
