### ISSUE TITLE
Object Capture

### ISSUE THREAD

**Issue by smaragdus** [henrypp/freeshooter#19]
Using [Free Shooter](https://www.henrypp.org/product/freeshooter) I was unable to capture tray controls with sub-menus like this (the screen-shot was taken with another program):

![sshot-2018-07-17- 02-36-15](https://user-images.githubusercontent.com/9025757/42788874-c85de746-896a-11e8-87a1-c2dabd80b4fb.png)

Perhaps for capturing such objects with sub-menus (drop-down menus) it would be better to have a new capture mode:

- _Screenshot: object_

which allows the user to select the multiple objects (cascading menus), perhaps via 'CTRL+Click' and then 'Enter' to take the screen-shot after the menus have been selected.

**Comment by henrypp** [comment]
![sshot- s2018-07-17-20-53-21](https://user-images.githubusercontent.com/3902025/42825264-73ae65d8-8a03-11e8-9572-ced42f65d6d9.png)
Screenshoot taken by Free Shooter through "window mode" (Ctrl+Prnt scrn hotkey)

**Comment by smaragdus** [comment]
Free Shooter can take such screen-shots ( 2 objects- menu plus single sub-menu) but it fails to capture objects with 2 sub-menus. Try to take a screen like mine with 2 sub-menus (3-object-capture), I will attach the archive containing the program I used to illustrate the problem..

[minibin.zip](https://github.com/henrypp/freeshooter/files/2203353/minibin.zip)

Using 'active window' I was able to capture only 2 objects together, not 3 objects.

**Comment by henrypp** [comment]
![sshot-2018-07-18-13-39-20](https://user-images.githubusercontent.com/3902025/42866978-fcb1f322-8a8f-11e8-9060-905499e1df53.png)
fixed

**Comment by henrypp** [comment]
![sshot-2018-07-18-13-51-38](https://user-images.githubusercontent.com/3902025/42867543-b8e03be8-8a91-11e8-9a6a-186dcd201ef5.png)

**Comment by smaragdus** [comment]
@henrypp 
I can confirm that version [2.0.5](https://github.com/henrypp/freeshooter/releases/tag/v.2.0.5) was able to take such screen-shots:

![sshot-2018-07-19-04-26-22](https://user-images.githubusercontent.com/9025757/42916118-4622df22-8b0c-11e8-99ca-910752b92c62.png)

The difference between [the other screen-shot](https://user-images.githubusercontent.com/9025757/42788874-c85de746-896a-11e8-87a1-c2dabd80b4fb.png) and [this screen-shot](https://user-images.githubusercontent.com/9025757/42916118-4622df22-8b0c-11e8-99ca-910752b92c62.png) is that the first one is without background while the second one (taken by **Free Shooter**) has white background. Is there a way to capture menus and sub-menus without white background?

**Comment by henrypp** [comment]
> Clear window background

Option

**Comment by smaragdus** [comment]
@henrypp 

Thanks, but if 'Clear window background' is disabled then **Free Shooter** captures desktop background. My idea was capturing only the cascading menus without any background.
