### ISSUE TITLE
Update Spanish.ini

### ISSUE THREAD

**Issue by c-sanchez** [henrypp/freeshooter#20]
I'm a bit new with how works github, I did a copy of freeshooter repository to update the Spanish.ini

https://github.com/c-sanchez/freeshooter/blob/840c1be24d7180d600000da7a41c43e431b76a12/bin/i18n/Spanish.ini

I guess is better if I can modify this file directly in the freeshooter repository or if I can make a merge request or something.
I've used previously the option "Commit directly to the master branch." but I don't know if this notify or what.

**Comment by henrypp** [comment]
If you cant understant github merge, you can send Spanish.ini file directly to my email.
