### ISSUE TITLE
Every time I open freeshooter I get notice of a language pact update.

### ISSUE THREAD

**Issue by ghost** [henrypp/freeshooter#25]
I have version 2.0.7 64 bit (unicode) and I love it.  But each time I open it I get a notice of a language pack update from last March.  I update it, it says it was downloaded, but when I open it again I get the same notice.

**Comment by RayPS** [comment]
same

**Comment by andika207** [comment]
same here, every time I start up Windows I get the updating message but I don't hit the accept button.
is there a way to avoid this stupid message if I don't want it to auto check for new updates ?
why don't you just compile it again with the language pack inside ?

**Comment by henrypp** [comment]
@andika207, disable update check?
