### ISSUE TITLE
Implement a timer feature

### ISSUE THREAD

**Issue by Janaue** [henrypp/freeshooter#27]
Sometimes I want to take picture of a a window appearing while the mouse hovers over some link in some program, so as soon as I move the cursor, i love this floating window. Sometimes I use a keyboard shortcut to trigger the capture of the screen with your program, but sometimes this does not work, so my idea is to have an option for a timer.

**Comment by arleenlasleur** [comment]
Upvote.

@Janaue, for now I'm using AHK.
