### ISSUE TITLE
The result with "VirusTotal" are not good.

### ISSUE THREAD

**Issue by Shitennouji** [henrypp/freeshooter#29]
<img width="402" alt="sshot-2019-11-20-04-56-12" src="https://user-images.githubusercontent.com/5517475/69232937-f514d700-0b59-11ea-8969-ca1ffa1deed1.png">

Free Shooter | https://www.henrypp.org/product/freeshooter | 
16 engines detected this file：
https://www.virustotal.com/gui/file/9baaeffd561655696a6f925b6a2e166bb0e06897cec2b84d3e36cbbdc6a9efff/detection

https://www.virustotal.com/gui/url/3d04cdc3638790c1a00266a68a74d738a954e166e0527ef5a443156dcba70998/detection

13 engines detected this file：
https://www.virustotal.com/gui/file/40fcfb4bfb443b2c6322814ffbffde0a8d80905d01a9b5222b8fb83fd2e8bf61/detection

https://www.virustotal.com/gui/url/477bd703154fc992b841587d7b56ebcb9959bef28372bff6d7efeb620442ad4a/detection

freeshooter Release v.2.0.7 |  GitHub |  
https://github.com/henrypp/freeshooter/releases/tag/v.2.0.7
16 engines detected this file：
https://www.virustotal.com/gui/file/9baaeffd561655696a6f925b6a2e166bb0e06897cec2b84d3e36cbbdc6a9efff/detection

https://www.virustotal.com/gui/url/f8a66e6551c9f08b16e9b185183a20fa5324cbf445e11f42c7581fd16fe32d82/detection

13 engines detected this file：
https://www.virustotal.com/gui/file/40fcfb4bfb443b2c6322814ffbffde0a8d80905d01a9b5222b8fb83fd2e8bf61/detection

https://www.virustotal.com/gui/url/943ef9fa12521388928afc34d345f841b39ff8b09db0f3b1c58478a95e469045/detection

When I checked Details, 
they seem to have a problem with "Signature verification".

GPG Signature
Public key: pubkey.asc (ha.pool.sks-keyservers.net)
Key ID: 0x5635B5FD
Fingerprint: D985 2361 1524 AB29 BE73 30AC 2881 20A7 5635 B5FD
Search results for '0x5635b5fd' | sks-keyservers.net | 
http://ha.pool.sks-keyservers.net/pks/lookup?op=vindex&fingerprint=on&search=0x5635b5fd

The “digital signature” has expired.

**Comment by Shitennouji** [comment]
VirusTotal judgments upset end users.

**Comment by smaragdus** [comment]
> VirusTotal results are likely to confuse many end users.

If  there are users who are so confused to use Google-owned spyware VirusTotal they deserve to get even more confused.

**Comment by Shitennouji** [comment]
> If there are users who are so confused to use Google-owned spyware VirusTotal they deserve to get even more confused.

Whatever the owner of VirusTotal,
VirusTotal aggregates many antivirus products and online scan engines to check for viruses that the user's own antivirus may have missed, or to verify against any false positives.

First, the results should be scrutinized.
freeshooter-2.0.7-bin.zip
16 engines detected this file：
https://www.virustotal.com/gui/file/9baaeffd561655696a6f925b6a2e166bb0e06897cec2b84d3e36cbbdc6a9efff/detection

freeshooter-2.0.7-setup.exe
13 engines detected this file：
https://www.virustotal.com/gui/file/40fcfb4bfb443b2c6322814ffbffde0a8d80905d01a9b5222b8fb83fd2e8bf61/detection

Isn't it necessary to take some measures based on these?
For example, 
the declaration “VirusTotal is unreliable. Don't worry about those results because it guarantees no danger at all.”
“Because a download file is provided that is managed by the developer, there is no contamination of third party bundles or malware. 100% security is guaranteed.”

It would be better to make an “official” announcement on the homepage.

**Comment by henrypp** [comment]
> “VirusTotal is unreliable. Don't worry about those results because it guarantees no danger at all.”

Lol, humanity, who can read this, i can count by fingers of one hand.

> It would be better to make an “official” announcement on the homepage.

hmm... checksum, gpg signature, it was published to check binaries is not changed by thirdparty peoples. i think it' s enough, anything else is helpless.

![sshot-002](https://user-images.githubusercontent.com/3902025/69265132-ddd5f800-0bf2-11ea-918b-8a49b486ebc4.png)

Interresting, because it's same binaries, why him are mistake (16/13).

**Comment by Shitennouji** [comment]
> checksum, gpg signature, it was published to check binaries is not changed by thirdparty.
> i think it' s more than enough.

You are right, I also agree with that point of view.
However, most end users are equal to ignorance.
Unfortunately, most common users trust "VirusTotal".
For this reason, I think we should not overlook the “false positive problem” that can lead to confusion.
In other words, 
On the official homepage “VirusTotal will determine that it is a false positive. However, checksums, gpg signatures, and binaries have been released to ensure that they have not been modified by a third party. I guarantee safety.” It is recommended to add the declaration.
It may be powerless to those who trust VirusTotal, but it will be effective as a “revelation”.

> Interesting, because it's same binaries, why him are mistake (16/13).

In general, zip files are difficult to scan and are prone to false positives.
In addition, “files” that are not registered with the security vendor are It will be false positives.

Many developers of the individual are headed by this “false positive problem”.
If it is a few percent on many engines, you can ignore it. That's why, I recommend the “official declaration” by the author.

**Comment by henrypp** [comment]
![fyi](https://user-images.githubusercontent.com/3902025/69488121-6bce0f00-0e8f-11ea-8e1a-dde5b6042ace.png)
