### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by whiggs** [henrypp/freeshooter#4]
To whom this may concern,
I wanted to make you aware of the fact that google chrome blocks this file and prevents it from downloading successfully.  Furthermore, after I tell google chrome to shove it and download it anyway, I sent the archive file to Virus total, and the results were disappointing.  12 antivirus engines flag your application as malware.  While I know first hand that antivirus products suck at detecting actual malware, and instead seem content with just flagging false positives, the number of flags is disconcerting.  I would highly recommend you either (or both) a) explain on the product page that the file may be flagged as malware but is safe (if it is, I haven't tried it because I am not convinced), or b) find out for yourself which antivirus engines are flagging your application, and email your application and source code to the developers of the antivirus software so they can see if it is malicious in nature and whitelist it in the next release of their virus definition updates.

**Comment by henrypp** [comment]
no virus anything.

**Comment by whiggs** [comment]
Sir.  My purpose in writing this was not to convince me that the product is not a virus.  Whether it is or not is irrelevant.  The fact of the matter is that pretty much all the major browsers BLOCK your application and prevent it from being downloaded.  That already reduces the number of people who will actually use your product by 85%, either because they were scared of the potential for getting infected or because they COULD NOT FIGURE OUT HOW TO UNBLOCK IT (they don't make it easy to figure out and for a reason).  Even if they do figure it out and manage to download your tool, it is highly likely that, according to the Virus total results, your tool will be quarantined automatically by their antivirus, and would have to go through the painstaking process of removing it from quarantine and adding an exception to their antivirus product.  If the antivirus malware detection doesn't scare off the other 10% of initially interested potential users that will not use your tool, then the sheer amount of effort involved in configuring the antivirus will.  I know I for one wouldn't go through the trouble just for a screenshot tool, and I think the rest of the world would agree.  My point here is, as the developer, if you want people to USE YOUR TOOL, you need to take steps to make it easier for them to use, because as of now, only 5% of the potential users who could be using your tool are. If you want more people to use your tool (which I assume it is or else why would you have shared it in the first freaking place), then you, as the developer, need to re-read my initial post and perform the steps I outlined so that the antivirus developers, and the developers of the browsers, will stop black listing your product and actually a) make it possible for your users to obtain your product and b) make them confident about using it.  Do me a favor and actually read the whole post instead of part of it.
