### ISSUE TITLE
[Bug] Update Feature Does Not Install, Asks Immediately On Logon & Repeatedly After if Update Setting is Checked

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [henrypp/freeshooter#42]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

2.0.7 x64

### Windows version

Windows 10 Enterprise LTSC (x64) Build 19044.1645 (21H2)

### Steps to reproduce

1. Be sure that Free Shooter .exe has internet access & is not blocked by any firewall
2. Have Free Shooter installed in portable mode 
3. Set program to launch at PC log-in
4. Check "Periodically check for updates" setting 
5. Either wait or restart PC, log-in
6. "Update available, do you want to install them?" - Click "Yes"
7. Wait ~3 seconds
8. "Update available, do you want to install them? - Click "Yes" Again

### Expected behavior

I would expect it to maybe ask about where the directory is located, but to download and install an update, as well as probably display a gui to visualize the status of said installation. 

### Actual behavior

![000090](https://github.com/henrypp/freeshooter/assets/99932128/84205fbf-2c0a-47c4-9d9f-e6081211fbca)

**Popup from Free Shooter is boxed in red**

**Hwinfo to demonstrate system info**

**Comment by henrypp** [comment]
fxd
