### ISSUE TITLE
[Bug] Pressing print screen key (or configured hotkey) freezes app

### ISSUE THREAD

**Issue by masterofobzene** [henrypp/freeshooter#43]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

123

### Windows version

10

### Steps to reproduce

try to take an area screenshot.
while on the overlay press the hotkey again
enjoy your softlock.

### Actual behavior

try to take an area screenshot.
while on the overlay press the hotkey again
enjoy your softlock.

**Comment by BismutoGanymedes** [comment]
When will the fixed version be out for download?

**Comment by henrypp** [comment]
@BismutoGanymedes soon, i hope
