### ISSUE TITLE
ВИРУС !

### ISSUE THREAD

**Issue by aiv3006** [henrypp/freeshooter#5]
![2017-05-11_110754](https://cloud.githubusercontent.com/assets/7733409/25936895/a28093a4-363a-11e7-9b22-941fe23386c8.png)

**Comment by aiv3006** [comment]
https://www.virustotal.com/ru/file/4730d48d1a6f5fdb7105e5cf812cd1be79ecafb56ad3e96c242c285a82330704/analysis/1494486888/

![default](https://cloud.githubusercontent.com/assets/7733409/25937047/48d629b2-363b-11e7-83b9-fdb534560996.png)

**Comment by henrypp** [comment]
no virus anything. stop it.

**Comment by aiv3006** [comment]
Проверь сам ;)) https://www.virustotal.com/ru/file/4730d48d1a6f5fdb7105e5cf812cd1be79ecafb56ad3e96c242c285a82330704/analysis/1494513199/

**Comment by henrypp** [comment]
uploadfile.dll больше нет в архиве.
